// This file has not only been generated automatically, it has also been patched automatically on top of that: All addresses have been multiplied by 4 to match the AMBA bus addressing


// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!         THIS FILE IS AUTOMATICALLY GENERATED         !!
// !!              DO NOT EDIT THIS FILE                   !!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#ifndef TMF8X2X_STATISTIC_REGISTERS_H
#define TMF8X2X_STATISTIC_REGISTERS_H

#define TMF8X2X_COM_STATISTICS_CFG_IDX 0x24
#define TMF8X2X_COM_STATISTICS_CFG_IDX__statistics_cfg_idx__MASK  0xff
#define TMF8X2X_COM_STATISTICS_CFG_IDX__statistics_cfg_idx__WIDTH 8
#define TMF8X2X_COM_STATISTICS_CFG_IDX__statistics_cfg_idx__SHIFT 0
#define TMF8X2X_COM_STATISTICS_CFG_IDX__statistics_cfg_idx__RESET 0

#define TMF8X2X_COM_TDCIF_STATUS 0x25
#define TMF8X2X_COM_TDCIF_STATUS__tdcif_status__MASK  0xffffffff
#define TMF8X2X_COM_TDCIF_STATUS__tdcif_status__WIDTH 32
#define TMF8X2X_COM_TDCIF_STATUS__tdcif_status__SHIFT 0
#define TMF8X2X_COM_TDCIF_STATUS__tdcif_status__RESET 0

#define TMF8X2X_COM_ITERATIONS_CONFIGURED 0x29
#define TMF8X2X_COM_ITERATIONS_CONFIGURED__iterations_configured__MASK  0xffffffff
#define TMF8X2X_COM_ITERATIONS_CONFIGURED__iterations_configured__WIDTH 32
#define TMF8X2X_COM_ITERATIONS_CONFIGURED__iterations_configured__SHIFT 0
#define TMF8X2X_COM_ITERATIONS_CONFIGURED__iterations_configured__RESET 0

#define TMF8X2X_COM_REMAINING_ITERATIONS 0x2d
#define TMF8X2X_COM_REMAINING_ITERATIONS__remaining_iterations__MASK  0xffffffff
#define TMF8X2X_COM_REMAINING_ITERATIONS__remaining_iterations__WIDTH 32
#define TMF8X2X_COM_REMAINING_ITERATIONS__remaining_iterations__SHIFT 0
#define TMF8X2X_COM_REMAINING_ITERATIONS__remaining_iterations__RESET 0

#define TMF8X2X_COM_ACCUMULATED_HITS 0x31
#define TMF8X2X_COM_ACCUMULATED_HITS__accumulated_hits__MASK  0xffffffff
#define TMF8X2X_COM_ACCUMULATED_HITS__accumulated_hits__WIDTH 32
#define TMF8X2X_COM_ACCUMULATED_HITS__accumulated_hits__SHIFT 0
#define TMF8X2X_COM_ACCUMULATED_HITS__accumulated_hits__RESET 0

#define TMF8X2X_COM_RAW_HITS_TDC0 0x35
#define TMF8X2X_COM_RAW_HITS_TDC0__raw_hits_tdc0__MASK  0xffffffff
#define TMF8X2X_COM_RAW_HITS_TDC0__raw_hits_tdc0__WIDTH 32
#define TMF8X2X_COM_RAW_HITS_TDC0__raw_hits_tdc0__SHIFT 0
#define TMF8X2X_COM_RAW_HITS_TDC0__raw_hits_tdc0__RESET 0

#define TMF8X2X_COM_RAW_HITS_TDC1 0x39
#define TMF8X2X_COM_RAW_HITS_TDC1__raw_hits_tdc1__MASK  0xffffffff
#define TMF8X2X_COM_RAW_HITS_TDC1__raw_hits_tdc1__WIDTH 32
#define TMF8X2X_COM_RAW_HITS_TDC1__raw_hits_tdc1__SHIFT 0
#define TMF8X2X_COM_RAW_HITS_TDC1__raw_hits_tdc1__RESET 0

#define TMF8X2X_COM_RAW_HITS_TDC2 0x3d
#define TMF8X2X_COM_RAW_HITS_TDC2__raw_hits_tdc2__MASK  0xffffffff
#define TMF8X2X_COM_RAW_HITS_TDC2__raw_hits_tdc2__WIDTH 32
#define TMF8X2X_COM_RAW_HITS_TDC2__raw_hits_tdc2__SHIFT 0
#define TMF8X2X_COM_RAW_HITS_TDC2__raw_hits_tdc2__RESET 0

#define TMF8X2X_COM_RAW_HITS_TDC3 0x41
#define TMF8X2X_COM_RAW_HITS_TDC3__raw_hits_tdc3__MASK  0xffffffff
#define TMF8X2X_COM_RAW_HITS_TDC3__raw_hits_tdc3__WIDTH 32
#define TMF8X2X_COM_RAW_HITS_TDC3__raw_hits_tdc3__SHIFT 0
#define TMF8X2X_COM_RAW_HITS_TDC3__raw_hits_tdc3__RESET 0

#define TMF8X2X_COM_RAW_HITS_TDC4 0x45
#define TMF8X2X_COM_RAW_HITS_TDC4__raw_hits_tdc4__MASK  0xffffffff
#define TMF8X2X_COM_RAW_HITS_TDC4__raw_hits_tdc4__WIDTH 32
#define TMF8X2X_COM_RAW_HITS_TDC4__raw_hits_tdc4__SHIFT 0
#define TMF8X2X_COM_RAW_HITS_TDC4__raw_hits_tdc4__RESET 0

#define TMF8X2X_COM_SATURATION_CNT_TDC0 0x49
#define TMF8X2X_COM_SATURATION_CNT_TDC0__saturation_cnt_tdc0__MASK  0xffffffff
#define TMF8X2X_COM_SATURATION_CNT_TDC0__saturation_cnt_tdc0__WIDTH 32
#define TMF8X2X_COM_SATURATION_CNT_TDC0__saturation_cnt_tdc0__SHIFT 0
#define TMF8X2X_COM_SATURATION_CNT_TDC0__saturation_cnt_tdc0__RESET 0

#define TMF8X2X_COM_SATURATION_CNT_TDC1 0x4d
#define TMF8X2X_COM_SATURATION_CNT_TDC1__saturation_cnt_tdc1__MASK  0xffffffff
#define TMF8X2X_COM_SATURATION_CNT_TDC1__saturation_cnt_tdc1__WIDTH 32
#define TMF8X2X_COM_SATURATION_CNT_TDC1__saturation_cnt_tdc1__SHIFT 0
#define TMF8X2X_COM_SATURATION_CNT_TDC1__saturation_cnt_tdc1__RESET 0

#define TMF8X2X_COM_SATURATION_CNT_TDC2 0x51
#define TMF8X2X_COM_SATURATION_CNT_TDC2__saturation_cnt_tdc2__MASK  0xffffffff
#define TMF8X2X_COM_SATURATION_CNT_TDC2__saturation_cnt_tdc2__WIDTH 32
#define TMF8X2X_COM_SATURATION_CNT_TDC2__saturation_cnt_tdc2__SHIFT 0
#define TMF8X2X_COM_SATURATION_CNT_TDC2__saturation_cnt_tdc2__RESET 0

#define TMF8X2X_COM_SATURATION_CNT_TDC3 0x55
#define TMF8X2X_COM_SATURATION_CNT_TDC3__saturation_cnt_tdc3__MASK  0xffffffff
#define TMF8X2X_COM_SATURATION_CNT_TDC3__saturation_cnt_tdc3__WIDTH 32
#define TMF8X2X_COM_SATURATION_CNT_TDC3__saturation_cnt_tdc3__SHIFT 0
#define TMF8X2X_COM_SATURATION_CNT_TDC3__saturation_cnt_tdc3__RESET 0

#define TMF8X2X_COM_SATURATION_CNT_TDC4 0x59
#define TMF8X2X_COM_SATURATION_CNT_TDC4__saturation_cnt_tdc4__MASK  0xffffffff
#define TMF8X2X_COM_SATURATION_CNT_TDC4__saturation_cnt_tdc4__WIDTH 32
#define TMF8X2X_COM_SATURATION_CNT_TDC4__saturation_cnt_tdc4__SHIFT 0
#define TMF8X2X_COM_SATURATION_CNT_TDC4__saturation_cnt_tdc4__RESET 0

#endif // TMF8X2X_STATISTIC_REGISTERS_H
