// This file has not only been generated automatically, it has also been patched automatically on top of that: All addresses have been multiplied by 4 to match the AMBA bus addressing


// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!         THIS FILE IS AUTOMATICALLY GENERATED         !!
// !!              DO NOT EDIT THIS FILE                   !!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#ifndef TMF8X2X_CONFIG_PAGE_FACTORY_H
#define TMF8X2X_CONFIG_PAGE_FACTORY_H

#define TMF8X2X_COM_FACTORY_CALIBRATION_FIRST 0x24
#define TMF8X2X_COM_FACTORY_CALIBRATION_FIRST__factory_calibration_first__MASK  0xff
#define TMF8X2X_COM_FACTORY_CALIBRATION_FIRST__factory_calibration_first__WIDTH 8
#define TMF8X2X_COM_FACTORY_CALIBRATION_FIRST__factory_calibration_first__SHIFT 0
#define TMF8X2X_COM_FACTORY_CALIBRATION_FIRST__factory_calibration_first__RESET 0

#define TMF8X2X_COM_FACTORY_CALIBRATION_LAST 0xdf
#define TMF8X2X_COM_FACTORY_CALIBRATION_LAST__factory_calibration_last__MASK  0xff
#define TMF8X2X_COM_FACTORY_CALIBRATION_LAST__factory_calibration_last__WIDTH 8
#define TMF8X2X_COM_FACTORY_CALIBRATION_LAST__factory_calibration_last__SHIFT 0
#define TMF8X2X_COM_FACTORY_CALIBRATION_LAST__factory_calibration_last__RESET 0

#endif // TMF8X2X_CONFIG_PAGE_FACTORY_H
