// This file has not only been generated automatically, it has also been patched automatically on top of that: All addresses have been multiplied by 4 to match the AMBA bus addressing


// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!         THIS FILE IS AUTOMATICALLY GENERATED         !!
// !!              DO NOT EDIT THIS FILE                   !!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#ifndef TMF8X2X_CONFIG_PAGE_COMMON_H
#define TMF8X2X_CONFIG_PAGE_COMMON_H

#define TMF8X2X_COM_PERIOD_MS_LSB 0x24
#define TMF8X2X_COM_PERIOD_MS_LSB__period_7_0__MASK  0xff
#define TMF8X2X_COM_PERIOD_MS_LSB__period_7_0__WIDTH 8
#define TMF8X2X_COM_PERIOD_MS_LSB__period_7_0__SHIFT 0
#define TMF8X2X_COM_PERIOD_MS_LSB__period_7_0__RESET 33

#define TMF8X2X_COM_PERIOD_MS_MSB 0x25
#define TMF8X2X_COM_PERIOD_MS_MSB__period_15_8__MASK  0xff
#define TMF8X2X_COM_PERIOD_MS_MSB__period_15_8__WIDTH 8
#define TMF8X2X_COM_PERIOD_MS_MSB__period_15_8__SHIFT 0
#define TMF8X2X_COM_PERIOD_MS_MSB__period_15_8__RESET 0

#define TMF8X2X_COM_KILO_ITERATIONS_LSB 0x26
#define TMF8X2X_COM_KILO_ITERATIONS_LSB__iterations_7_0__MASK  0xff
#define TMF8X2X_COM_KILO_ITERATIONS_LSB__iterations_7_0__WIDTH 8
#define TMF8X2X_COM_KILO_ITERATIONS_LSB__iterations_7_0__SHIFT 0
#define TMF8X2X_COM_KILO_ITERATIONS_LSB__iterations_7_0__RESET 25

#define TMF8X2X_COM_KILO_ITERATIONS_MSB 0x27
#define TMF8X2X_COM_KILO_ITERATIONS_MSB__iterations_15_8__MASK  0xff
#define TMF8X2X_COM_KILO_ITERATIONS_MSB__iterations_15_8__WIDTH 8
#define TMF8X2X_COM_KILO_ITERATIONS_MSB__iterations_15_8__SHIFT 0
#define TMF8X2X_COM_KILO_ITERATIONS_MSB__iterations_15_8__RESET 2

#define TMF8X2X_COM_INT_THRESHOLD_LOW_LSB 0x28
#define TMF8X2X_COM_INT_THRESHOLD_LOW_LSB__int_threshold_low_7_0__MASK  0xff
#define TMF8X2X_COM_INT_THRESHOLD_LOW_LSB__int_threshold_low_7_0__WIDTH 8
#define TMF8X2X_COM_INT_THRESHOLD_LOW_LSB__int_threshold_low_7_0__SHIFT 0
#define TMF8X2X_COM_INT_THRESHOLD_LOW_LSB__int_threshold_low_7_0__RESET 0

#define TMF8X2X_COM_INT_THRESHOLD_LOW_MSB 0x29
#define TMF8X2X_COM_INT_THRESHOLD_LOW_MSB__int_threshold_low_15_8__MASK  0xff
#define TMF8X2X_COM_INT_THRESHOLD_LOW_MSB__int_threshold_low_15_8__WIDTH 8
#define TMF8X2X_COM_INT_THRESHOLD_LOW_MSB__int_threshold_low_15_8__SHIFT 0
#define TMF8X2X_COM_INT_THRESHOLD_LOW_MSB__int_threshold_low_15_8__RESET 0

#define TMF8X2X_COM_INT_THRESHOLD_HIGH_LSB 0x2a
#define TMF8X2X_COM_INT_THRESHOLD_HIGH_LSB__int_threshold_high_7_0__MASK  0xff
#define TMF8X2X_COM_INT_THRESHOLD_HIGH_LSB__int_threshold_high_7_0__WIDTH 8
#define TMF8X2X_COM_INT_THRESHOLD_HIGH_LSB__int_threshold_high_7_0__SHIFT 0
#define TMF8X2X_COM_INT_THRESHOLD_HIGH_LSB__int_threshold_high_7_0__RESET 255

#define TMF8X2X_COM_INT_THRESHOLD_HIGH_MSB 0x2b
#define TMF8X2X_COM_INT_THRESHOLD_HIGH_MSB__int_threshold_high_15_8__MASK  0xff
#define TMF8X2X_COM_INT_THRESHOLD_HIGH_MSB__int_threshold_high_15_8__WIDTH 8
#define TMF8X2X_COM_INT_THRESHOLD_HIGH_MSB__int_threshold_high_15_8__SHIFT 0
#define TMF8X2X_COM_INT_THRESHOLD_HIGH_MSB__int_threshold_high_15_8__RESET 255

#define TMF8X2X_COM_INT_ZONE_MASK_0 0x2c
#define TMF8X2X_COM_INT_ZONE_MASK_0__int_zone_mask_7_0__MASK  0xff
#define TMF8X2X_COM_INT_ZONE_MASK_0__int_zone_mask_7_0__WIDTH 8
#define TMF8X2X_COM_INT_ZONE_MASK_0__int_zone_mask_7_0__SHIFT 0
#define TMF8X2X_COM_INT_ZONE_MASK_0__int_zone_mask_7_0__RESET 0

#define TMF8X2X_COM_INT_ZONE_MASK_1 0x2d
#define TMF8X2X_COM_INT_ZONE_MASK_1__int_zone_mask_15_8__MASK  0xff
#define TMF8X2X_COM_INT_ZONE_MASK_1__int_zone_mask_15_8__WIDTH 8
#define TMF8X2X_COM_INT_ZONE_MASK_1__int_zone_mask_15_8__SHIFT 0
#define TMF8X2X_COM_INT_ZONE_MASK_1__int_zone_mask_15_8__RESET 0

#define TMF8X2X_COM_INT_ZONE_MASK_2 0x2e
#define TMF8X2X_COM_INT_ZONE_MASK_2__int_zone_mask_17_16__MASK  0x3
#define TMF8X2X_COM_INT_ZONE_MASK_2__int_zone_mask_17_16__WIDTH 2
#define TMF8X2X_COM_INT_ZONE_MASK_2__int_zone_mask_17_16__SHIFT 0
#define TMF8X2X_COM_INT_ZONE_MASK_2__int_zone_mask_17_16__RESET 0

#define TMF8X2X_COM_INT_PERSISTENCE 0x2f
#define TMF8X2X_COM_INT_PERSISTENCE__int_persistence__MASK  0xff
#define TMF8X2X_COM_INT_PERSISTENCE__int_persistence__WIDTH 8
#define TMF8X2X_COM_INT_PERSISTENCE__int_persistence__SHIFT 0
#define TMF8X2X_COM_INT_PERSISTENCE__int_persistence__RESET 0

#define TMF8X2X_COM_CONFIDENCE_THRESHOLD 0x30
#define TMF8X2X_COM_CONFIDENCE_THRESHOLD__confidence_threshold__MASK  0xff
#define TMF8X2X_COM_CONFIDENCE_THRESHOLD__confidence_threshold__WIDTH 8
#define TMF8X2X_COM_CONFIDENCE_THRESHOLD__confidence_threshold__SHIFT 0
#define TMF8X2X_COM_CONFIDENCE_THRESHOLD__confidence_threshold__RESET 6

#define TMF8X2X_COM_GPIO_0 0x31
#define TMF8X2X_COM_GPIO_0__gpio0__MASK  0x7
#define TMF8X2X_COM_GPIO_0__gpio0__WIDTH 3
#define TMF8X2X_COM_GPIO_0__gpio0__SHIFT 0
#define TMF8X2X_COM_GPIO_0__gpio0__RESET 0
// Enumeration for gpio0
#define TMF8X2X_COM_GPIO_0__gpio0__TRISTATE 0 // pin is in tristate 						
#define TMF8X2X_COM_GPIO_0__gpio0__INPUT_ACTIVE_HIGH 1 // pin is input and active high 				
#define TMF8X2X_COM_GPIO_0__gpio0__INPUT_ACTIVE_LOW 2 // pin is input active low  					
#define TMF8X2X_COM_GPIO_0__gpio0__OUTPUT_LOW_VCSEL_PULSING 3 // pin is output low while VCSEL is pulsing 	
#define TMF8X2X_COM_GPIO_0__gpio0__OUTPUT_HIGH_VCSEL_PULSING 4 // pin is output high while VCSEL pulsing	
#define TMF8X2X_COM_GPIO_0__gpio0__OUTPUT_HIGH 5 // pin is constant high						
#define TMF8X2X_COM_GPIO_0__gpio0__OUTPUT_LOW 6 // pin is constant low 						

#define TMF8X2X_COM_GPIO_0__pre_delay0__MASK  0x18
#define TMF8X2X_COM_GPIO_0__pre_delay0__WIDTH 2
#define TMF8X2X_COM_GPIO_0__pre_delay0__SHIFT 3
#define TMF8X2X_COM_GPIO_0__pre_delay0__RESET 0
// Enumeration for pre_delay0
#define TMF8X2X_COM_GPIO_0__pre_delay0__NO_PREDELAY 0 // No predelay  					
#define TMF8X2X_COM_GPIO_0__pre_delay0__100_US_PREDELAY 1 // 100 microseconds pre-delay 	
#define TMF8X2X_COM_GPIO_0__pre_delay0__200_US_PREDELAY 2 // 200 microseconds pre-delay 	

#define TMF8X2X_COM_GPIO_0__driver_strength0__MASK  0xc0
#define TMF8X2X_COM_GPIO_0__driver_strength0__WIDTH 2
#define TMF8X2X_COM_GPIO_0__driver_strength0__SHIFT 6
#define TMF8X2X_COM_GPIO_0__driver_strength0__RESET 0
// Enumeration for driver_strength0
#define TMF8X2X_COM_GPIO_0__driver_strength0__DRIVING_STRENGTH_1X 0 // driving strength 1x       
#define TMF8X2X_COM_GPIO_0__driver_strength0__DRIVING_STREMGTH_2X 1 // driving strength 2x       
#define TMF8X2X_COM_GPIO_0__driver_strength0__DRIVING_STRENGTH_4X 2 // driving strength 4x       
#define TMF8X2X_COM_GPIO_0__driver_strength0__DRIVING_STRENGTH_7X 3 // driving strength 7x 		


#define TMF8X2X_COM_GPIO_1 0x32
#define TMF8X2X_COM_GPIO_1__gpio1__MASK  0x7
#define TMF8X2X_COM_GPIO_1__gpio1__WIDTH 3
#define TMF8X2X_COM_GPIO_1__gpio1__SHIFT 0
#define TMF8X2X_COM_GPIO_1__gpio1__RESET 0
// Enumeration for gpio1
#define TMF8X2X_COM_GPIO_1__gpio1__TRISTATE 0 // pin is in tristate 						
#define TMF8X2X_COM_GPIO_1__gpio1__INPUT_ACTIVE_HIGH 1 // pin is input and active high 				
#define TMF8X2X_COM_GPIO_1__gpio1__INPUT_ACTIVE_LOW 2 // pin is input active low  					
#define TMF8X2X_COM_GPIO_1__gpio1__OUTPUT_LOW_VCSEL_PULSING 3 // pin is output low while VCSEL is pulsing 	
#define TMF8X2X_COM_GPIO_1__gpio1__OUTPUT_HIGH_VCSEL_PULSING 4 // pin is output high while VCSEL pulsing	
#define TMF8X2X_COM_GPIO_1__gpio1__OUTPUT_HIGH 5 // pin is constant high						
#define TMF8X2X_COM_GPIO_1__gpio1__OUTPUT_LOW 6 // pin is constant low 						

#define TMF8X2X_COM_GPIO_1__pre_delay1__MASK  0x18
#define TMF8X2X_COM_GPIO_1__pre_delay1__WIDTH 2
#define TMF8X2X_COM_GPIO_1__pre_delay1__SHIFT 3
#define TMF8X2X_COM_GPIO_1__pre_delay1__RESET 0
// Enumeration for pre_delay1
#define TMF8X2X_COM_GPIO_1__pre_delay1__none 0 // No predelay  					
#define TMF8X2X_COM_GPIO_1__pre_delay1__100_us_predelay 1 // 100 microseconds pre-delay 	
#define TMF8X2X_COM_GPIO_1__pre_delay1__200_us_predelay 2 // 200 microseconds pre-delay 	

#define TMF8X2X_COM_GPIO_1__driver_strength1__MASK  0xc0
#define TMF8X2X_COM_GPIO_1__driver_strength1__WIDTH 2
#define TMF8X2X_COM_GPIO_1__driver_strength1__SHIFT 6
#define TMF8X2X_COM_GPIO_1__driver_strength1__RESET 0
// Enumeration for driver_strength1
#define TMF8X2X_COM_GPIO_1__driver_strength1__DRIVING_STRENGTH_1X 0 // driving strength 1x       
#define TMF8X2X_COM_GPIO_1__driver_strength1__DRIVING_STREMGTH_2X 1 // driving strength 2x       
#define TMF8X2X_COM_GPIO_1__driver_strength1__DRIVING_STRENGTH_4X 2 // driving strength 4x       
#define TMF8X2X_COM_GPIO_1__driver_strength1__DRIVING_STRENGTH_7X 3 // driving strength 7x 		


#define TMF8X2X_COM_POWER_CFG 0x33
#define TMF8X2X_COM_POWER_CFG__pulse_interrupt__MASK  0x4
#define TMF8X2X_COM_POWER_CFG__pulse_interrupt__WIDTH 1
#define TMF8X2X_COM_POWER_CFG__pulse_interrupt__SHIFT 2
#define TMF8X2X_COM_POWER_CFG__pulse_interrupt__RESET 0
#define TMF8X2X_COM_POWER_CFG__pulse_interrupt 4
#define TMF8X2X_COM_POWER_CFG__allow_osc_retrim__MASK  0x8
#define TMF8X2X_COM_POWER_CFG__allow_osc_retrim__WIDTH 1
#define TMF8X2X_COM_POWER_CFG__allow_osc_retrim__SHIFT 3
#define TMF8X2X_COM_POWER_CFG__allow_osc_retrim__RESET 0
#define TMF8X2X_COM_POWER_CFG__allow_osc_retrim 8
#define TMF8X2X_COM_POWER_CFG__keep_pll_running__MASK  0x20
#define TMF8X2X_COM_POWER_CFG__keep_pll_running__WIDTH 1
#define TMF8X2X_COM_POWER_CFG__keep_pll_running__SHIFT 5
#define TMF8X2X_COM_POWER_CFG__keep_pll_running__RESET 0
#define TMF8X2X_COM_POWER_CFG__keep_pll_running 32
#define TMF8X2X_COM_POWER_CFG__low_power_osc_on__MASK  0x40
#define TMF8X2X_COM_POWER_CFG__low_power_osc_on__WIDTH 1
#define TMF8X2X_COM_POWER_CFG__low_power_osc_on__SHIFT 6
#define TMF8X2X_COM_POWER_CFG__low_power_osc_on__RESET 0
#define TMF8X2X_COM_POWER_CFG__low_power_osc_on 64
#define TMF8X2X_COM_POWER_CFG__goto_standby_timed__MASK  0x80
#define TMF8X2X_COM_POWER_CFG__goto_standby_timed__WIDTH 1
#define TMF8X2X_COM_POWER_CFG__goto_standby_timed__SHIFT 7
#define TMF8X2X_COM_POWER_CFG__goto_standby_timed__RESET 0
#define TMF8X2X_COM_POWER_CFG__goto_standby_timed 128

#define TMF8X2X_COM_SPAD_MAP_ID 0x34
#define TMF8X2X_COM_SPAD_MAP_ID__spad_map_id__MASK  0xf
#define TMF8X2X_COM_SPAD_MAP_ID__spad_map_id__WIDTH 4
#define TMF8X2X_COM_SPAD_MAP_ID__spad_map_id__SHIFT 0
#define TMF8X2X_COM_SPAD_MAP_ID__spad_map_id__RESET 1
// Enumeration for spad_map_id
#define TMF8X2X_COM_SPAD_MAP_ID__spad_map_id__map_no_0 0 // 1x9 map,size 1x9			0. Special test mode  				
#define TMF8X2X_COM_SPAD_MAP_ID__spad_map_id__map_no_1 1 // 3x3 map, size 14x6 		1. Normal Mode (29°x29°)  			
#define TMF8X2X_COM_SPAD_MAP_ID__spad_map_id__map_no_2 2 // 3x3 map, size 14x9 		2. Macro Mode (29°x43,5°)  			
#define TMF8X2X_COM_SPAD_MAP_ID__spad_map_id__map_no_3 3 // 3x3 map, size 14x9		3. Macro Mode (29°x43,5°) 			
#define TMF8X2X_COM_SPAD_MAP_ID__spad_map_id__map_no_4 4 // 4x4 map, size 14x9		4. Time-multiplexed, Normal/Macro Mode (29°x43,5°)	
#define TMF8X2X_COM_SPAD_MAP_ID__spad_map_id__map_no_5 5 // 4x4 map, size 14x9		5. Time-multiplexed, Normal/Macro Mode (29°x43,5°)	
#define TMF8X2X_COM_SPAD_MAP_ID__spad_map_id__map_no_6 6 // 3x3 map, size 18x10		6. Normal Mode (44°x48°) 			
#define TMF8X2X_COM_SPAD_MAP_ID__spad_map_id__map_no_7 7 // 4x4 map, size 18x10		7. Time-multiplexed, Normal Mode (44°x48°) 			
#define TMF8X2X_COM_SPAD_MAP_ID__spad_map_id__map_no_8 8 // 9 zones map, size 14x9	8. Normal/Macro Mode (29°x43,5°) 	
#define TMF8X2X_COM_SPAD_MAP_ID__spad_map_id__map_no_9 9 // 9 zones map, size 14x9	9. Normal/Macro Mode (29°x43,5°) 	
#define TMF8X2X_COM_SPAD_MAP_ID__spad_map_id__map_no_10 10 // 3x6 map, size 18x12       10. Time-multiplexed, (29°x57°)  	
#define TMF8X2X_COM_SPAD_MAP_ID__spad_map_id__map_no_11 11 // 3x3 map, size 14x6        11. Checkerboard, Normal Mode(29°x29°) 				
#define TMF8X2X_COM_SPAD_MAP_ID__spad_map_id__map_no_12 12 // 3x3 map, size 14x6        12. Reverse-Checkerboard, Normal Mode(29°x29°) 				
#define TMF8X2X_COM_SPAD_MAP_ID__spad_map_id__map_no_13 13 // 4x4 map, size 18x8        13. Time-multiplexed, Narrow Mode (29°x39°) 				
#define TMF8X2X_COM_SPAD_MAP_ID__spad_map_id__user_defined_1 14 // user defined mask, single measurement mode (use config_page_spad_1 only)				
#define TMF8X2X_COM_SPAD_MAP_ID__spad_map_id__user_defined_2 15 // user defined mask, time multiplex mode (use config_page_spad_1 and config_page_spad_2) 


#define TMF8X2X_COM_ALG_SETTING_0 0x35
#define TMF8X2X_COM_ALG_SETTING_0__electrical_calibration__MASK  0x1
#define TMF8X2X_COM_ALG_SETTING_0__electrical_calibration__WIDTH 1
#define TMF8X2X_COM_ALG_SETTING_0__electrical_calibration__SHIFT 0
#define TMF8X2X_COM_ALG_SETTING_0__electrical_calibration__RESET 0
#define TMF8X2X_COM_ALG_SETTING_0__electrical_calibration 1
#define TMF8X2X_COM_ALG_SETTING_0__statistics__MASK  0x2
#define TMF8X2X_COM_ALG_SETTING_0__statistics__WIDTH 1
#define TMF8X2X_COM_ALG_SETTING_0__statistics__SHIFT 1
#define TMF8X2X_COM_ALG_SETTING_0__statistics__RESET 0
#define TMF8X2X_COM_ALG_SETTING_0__statistics 2
#define TMF8X2X_COM_ALG_SETTING_0__distances__MASK  0x4
#define TMF8X2X_COM_ALG_SETTING_0__distances__WIDTH 1
#define TMF8X2X_COM_ALG_SETTING_0__distances__SHIFT 2
#define TMF8X2X_COM_ALG_SETTING_0__distances__RESET 1
#define TMF8X2X_COM_ALG_SETTING_0__distances 4
#define TMF8X2X_COM_ALG_SETTING_0__distance_mode__MASK  0x18
#define TMF8X2X_COM_ALG_SETTING_0__distance_mode__WIDTH 2
#define TMF8X2X_COM_ALG_SETTING_0__distance_mode__SHIFT 3
#define TMF8X2X_COM_ALG_SETTING_0__distance_mode__RESET 0
#define TMF8X2X_COM_ALG_SETTING_0__diagnostics__MASK  0x40
#define TMF8X2X_COM_ALG_SETTING_0__diagnostics__WIDTH 1
#define TMF8X2X_COM_ALG_SETTING_0__diagnostics__SHIFT 6
#define TMF8X2X_COM_ALG_SETTING_0__diagnostics__RESET 0
#define TMF8X2X_COM_ALG_SETTING_0__diagnostics 64
#define TMF8X2X_COM_ALG_SETTING_0__increase_confidence_range__MASK  0x80
#define TMF8X2X_COM_ALG_SETTING_0__increase_confidence_range__WIDTH 1
#define TMF8X2X_COM_ALG_SETTING_0__increase_confidence_range__SHIFT 7
#define TMF8X2X_COM_ALG_SETTING_0__increase_confidence_range__RESET 0
#define TMF8X2X_COM_ALG_SETTING_0__increase_confidence_range 128

#define TMF8X2X_COM_ALG_SETTING_1 0x36
#define TMF8X2X_COM_ALG_SETTING_1__reserved_1__MASK  0xff
#define TMF8X2X_COM_ALG_SETTING_1__reserved_1__WIDTH 8
#define TMF8X2X_COM_ALG_SETTING_1__reserved_1__SHIFT 0
#define TMF8X2X_COM_ALG_SETTING_1__reserved_1__RESET 0

#define TMF8X2X_COM_ALG_SETTING_2 0x37
#define TMF8X2X_COM_ALG_SETTING_2__reserved_2__MASK  0xff
#define TMF8X2X_COM_ALG_SETTING_2__reserved_2__WIDTH 8
#define TMF8X2X_COM_ALG_SETTING_2__reserved_2__SHIFT 0
#define TMF8X2X_COM_ALG_SETTING_2__reserved_2__RESET 0

#define TMF8X2X_COM_ALG_SETTING_3 0x38
#define TMF8X2X_COM_ALG_SETTING_3__reserved_3__MASK  0xff
#define TMF8X2X_COM_ALG_SETTING_3__reserved_3__WIDTH 8
#define TMF8X2X_COM_ALG_SETTING_3__reserved_3__SHIFT 0
#define TMF8X2X_COM_ALG_SETTING_3__reserved_3__RESET 0

#define TMF8X2X_COM_HIST_DUMP 0x39
#define TMF8X2X_COM_HIST_DUMP__histogram__MASK  0x7f
#define TMF8X2X_COM_HIST_DUMP__histogram__WIDTH 7
#define TMF8X2X_COM_HIST_DUMP__histogram__SHIFT 0
#define TMF8X2X_COM_HIST_DUMP__histogram__RESET 0
// Enumeration for histogram
#define TMF8X2X_COM_HIST_DUMP__histogram__raw_24_bit_histogram 1 // Raw 24 bit histogram 		 				
#define TMF8X2X_COM_HIST_DUMP__histogram__electrical_calibration_24_bit_histogram 2 // Electrical calibration 24 bit histogram 	
#define TMF8X2X_COM_HIST_DUMP__histogram__reserved_0 4 // Reserved									
#define TMF8X2X_COM_HIST_DUMP__histogram__reserved_1 8 // Reserved                         			
#define TMF8X2X_COM_HIST_DUMP__histogram__reserved_2 16 // Reserved									
#define TMF8X2X_COM_HIST_DUMP__histogram__reserved_3 32 // Reserved									
#define TMF8X2X_COM_HIST_DUMP__histogram__breakpoint_hit 64 // This cannot be selected, it is used as a define only. 


#define TMF8X2X_COM_SPREAD_SPECTRUM 0x3a
#define TMF8X2X_COM_SPREAD_SPECTRUM__spread_spectrum__MASK  0xff
#define TMF8X2X_COM_SPREAD_SPECTRUM__spread_spectrum__WIDTH 8
#define TMF8X2X_COM_SPREAD_SPECTRUM__spread_spectrum__SHIFT 0
#define TMF8X2X_COM_SPREAD_SPECTRUM__spread_spectrum__RESET 0

#define TMF8X2X_COM_I2C_SLAVE_ADDRESS 0x3b
#define TMF8X2X_COM_I2C_SLAVE_ADDRESS__7bit_slave_address__MASK  0xfe
#define TMF8X2X_COM_I2C_SLAVE_ADDRESS__7bit_slave_address__WIDTH 7
#define TMF8X2X_COM_I2C_SLAVE_ADDRESS__7bit_slave_address__SHIFT 1
#define TMF8X2X_COM_I2C_SLAVE_ADDRESS__7bit_slave_address__RESET 130

#define TMF8X2X_COM_OSC_TRIM_VALUE_LSB 0x3c
#define TMF8X2X_COM_OSC_TRIM_VALUE_LSB__osc_trim_value_7_0__MASK  0xff
#define TMF8X2X_COM_OSC_TRIM_VALUE_LSB__osc_trim_value_7_0__WIDTH 8
#define TMF8X2X_COM_OSC_TRIM_VALUE_LSB__osc_trim_value_7_0__SHIFT 0
#define TMF8X2X_COM_OSC_TRIM_VALUE_LSB__osc_trim_value_7_0__RESET 0

#define TMF8X2X_COM_OSC_TRIM_VALUE_MSB 0x3d
#define TMF8X2X_COM_OSC_TRIM_VALUE_MSB__osc_trim_value_8_8__MASK  0x1
#define TMF8X2X_COM_OSC_TRIM_VALUE_MSB__osc_trim_value_8_8__WIDTH 1
#define TMF8X2X_COM_OSC_TRIM_VALUE_MSB__osc_trim_value_8_8__SHIFT 0
#define TMF8X2X_COM_OSC_TRIM_VALUE_MSB__osc_trim_value_8_8__RESET 0
#define TMF8X2X_COM_OSC_TRIM_VALUE_MSB__osc_trim_value_8_8 1

#define TMF8X2X_COM_I2C_ADDR_CHANGE 0x3e
#define TMF8X2X_COM_I2C_ADDR_CHANGE__gpio_change_value__MASK  0x3
#define TMF8X2X_COM_I2C_ADDR_CHANGE__gpio_change_value__WIDTH 2
#define TMF8X2X_COM_I2C_ADDR_CHANGE__gpio_change_value__SHIFT 0
#define TMF8X2X_COM_I2C_ADDR_CHANGE__gpio_change_value__RESET 0
#define TMF8X2X_COM_I2C_ADDR_CHANGE__gpio_change_mask__MASK  0xc
#define TMF8X2X_COM_I2C_ADDR_CHANGE__gpio_change_mask__WIDTH 2
#define TMF8X2X_COM_I2C_ADDR_CHANGE__gpio_change_mask__SHIFT 2
#define TMF8X2X_COM_I2C_ADDR_CHANGE__gpio_change_mask__RESET 0

#define TMF8X2X_COM_SPARE 0x3f
#define TMF8X2X_COM_SPARE__spare__MASK  0xff
#define TMF8X2X_COM_SPARE__spare__WIDTH 8
#define TMF8X2X_COM_SPARE__spare__SHIFT 0
#define TMF8X2X_COM_SPARE__spare__RESET 0

#define TMF8X2X_COM_ALG_ZOFFSET_0 0x40
#define TMF8X2X_COM_ALG_ZOFFSET_0__zoffset_0__MASK  0xff
#define TMF8X2X_COM_ALG_ZOFFSET_0__zoffset_0__WIDTH 8
#define TMF8X2X_COM_ALG_ZOFFSET_0__zoffset_0__SHIFT 0
#define TMF8X2X_COM_ALG_ZOFFSET_0__zoffset_0__RESET 205

#define TMF8X2X_COM_ALG_ZOFFSET_1 0x41
#define TMF8X2X_COM_ALG_ZOFFSET_1__zoffset_1__MASK  0xff
#define TMF8X2X_COM_ALG_ZOFFSET_1__zoffset_1__WIDTH 8
#define TMF8X2X_COM_ALG_ZOFFSET_1__zoffset_1__SHIFT 0
#define TMF8X2X_COM_ALG_ZOFFSET_1__zoffset_1__RESET 108

#define TMF8X2X_COM_ALG_ZOFFSET_2 0x42
#define TMF8X2X_COM_ALG_ZOFFSET_2__zoffset_2__MASK  0xff
#define TMF8X2X_COM_ALG_ZOFFSET_2__zoffset_2__WIDTH 8
#define TMF8X2X_COM_ALG_ZOFFSET_2__zoffset_2__SHIFT 0
#define TMF8X2X_COM_ALG_ZOFFSET_2__zoffset_2__RESET 0

#define TMF8X2X_COM_ALG_ZOFFSET_3 0x43
#define TMF8X2X_COM_ALG_ZOFFSET_3__zoffset_3__MASK  0xff
#define TMF8X2X_COM_ALG_ZOFFSET_3__zoffset_3__WIDTH 8
#define TMF8X2X_COM_ALG_ZOFFSET_3__zoffset_3__SHIFT 0
#define TMF8X2X_COM_ALG_ZOFFSET_3__zoffset_3__RESET 0

#define TMF8X2X_COM_ALG_X2COEFF_0 0x44
#define TMF8X2X_COM_ALG_X2COEFF_0__x2coeff_0__MASK  0xff
#define TMF8X2X_COM_ALG_X2COEFF_0__x2coeff_0__WIDTH 8
#define TMF8X2X_COM_ALG_X2COEFF_0__x2coeff_0__SHIFT 0
#define TMF8X2X_COM_ALG_X2COEFF_0__x2coeff_0__RESET 62

#define TMF8X2X_COM_ALG_X2COEFF_1 0x45
#define TMF8X2X_COM_ALG_X2COEFF_1__x2coeff_1__MASK  0xff
#define TMF8X2X_COM_ALG_X2COEFF_1__x2coeff_1__WIDTH 8
#define TMF8X2X_COM_ALG_X2COEFF_1__x2coeff_1__SHIFT 0
#define TMF8X2X_COM_ALG_X2COEFF_1__x2coeff_1__RESET 0

#define TMF8X2X_COM_ALG_X2COEFF_2 0x46
#define TMF8X2X_COM_ALG_X2COEFF_2__x2coeff_2__MASK  0xff
#define TMF8X2X_COM_ALG_X2COEFF_2__x2coeff_2__WIDTH 8
#define TMF8X2X_COM_ALG_X2COEFF_2__x2coeff_2__SHIFT 0
#define TMF8X2X_COM_ALG_X2COEFF_2__x2coeff_2__RESET 0

#define TMF8X2X_COM_ALG_X2COEFF_3 0x47
#define TMF8X2X_COM_ALG_X2COEFF_3__x2coeff_3__MASK  0xff
#define TMF8X2X_COM_ALG_X2COEFF_3__x2coeff_3__WIDTH 8
#define TMF8X2X_COM_ALG_X2COEFF_3__x2coeff_3__SHIFT 0
#define TMF8X2X_COM_ALG_X2COEFF_3__x2coeff_3__RESET 0

#define TMF8X2X_COM_ALG_XCOEFF_0 0x48
#define TMF8X2X_COM_ALG_XCOEFF_0__xcoeff_0__MASK  0xff
#define TMF8X2X_COM_ALG_XCOEFF_0__xcoeff_0__WIDTH 8
#define TMF8X2X_COM_ALG_XCOEFF_0__xcoeff_0__SHIFT 0
#define TMF8X2X_COM_ALG_XCOEFF_0__xcoeff_0__RESET 61

#define TMF8X2X_COM_ALG_XCOEFF_1 0x49
#define TMF8X2X_COM_ALG_XCOEFF_1__xcoeff_1__MASK  0xff
#define TMF8X2X_COM_ALG_XCOEFF_1__xcoeff_1__WIDTH 8
#define TMF8X2X_COM_ALG_XCOEFF_1__xcoeff_1__SHIFT 0
#define TMF8X2X_COM_ALG_XCOEFF_1__xcoeff_1__RESET 42

#define TMF8X2X_COM_ALG_XCOEFF_2 0x4a
#define TMF8X2X_COM_ALG_XCOEFF_2__xcoeff_2__MASK  0xff
#define TMF8X2X_COM_ALG_XCOEFF_2__xcoeff_2__WIDTH 8
#define TMF8X2X_COM_ALG_XCOEFF_2__xcoeff_2__SHIFT 0
#define TMF8X2X_COM_ALG_XCOEFF_2__xcoeff_2__RESET 0

#define TMF8X2X_COM_ALG_XCOEFF_3 0x4b
#define TMF8X2X_COM_ALG_XCOEFF_3__xcoeff_3__MASK  0xff
#define TMF8X2X_COM_ALG_XCOEFF_3__xcoeff_3__WIDTH 8
#define TMF8X2X_COM_ALG_XCOEFF_3__xcoeff_3__SHIFT 0
#define TMF8X2X_COM_ALG_XCOEFF_3__xcoeff_3__RESET 0

#define TMF8X2X_COM_ALG_ESTIMATEBIAS_0 0x4c
#define TMF8X2X_COM_ALG_ESTIMATEBIAS_0__estimate_bias_0__MASK  0xff
#define TMF8X2X_COM_ALG_ESTIMATEBIAS_0__estimate_bias_0__WIDTH 8
#define TMF8X2X_COM_ALG_ESTIMATEBIAS_0__estimate_bias_0__SHIFT 0
#define TMF8X2X_COM_ALG_ESTIMATEBIAS_0__estimate_bias_0__RESET 0

#define TMF8X2X_COM_ALG_ESTIMATEBIAS_1 0x4d
#define TMF8X2X_COM_ALG_ESTIMATEBIAS_1__estimate_bias_1__MASK  0xff
#define TMF8X2X_COM_ALG_ESTIMATEBIAS_1__estimate_bias_1__WIDTH 8
#define TMF8X2X_COM_ALG_ESTIMATEBIAS_1__estimate_bias_1__SHIFT 0
#define TMF8X2X_COM_ALG_ESTIMATEBIAS_1__estimate_bias_1__RESET 128

#define TMF8X2X_COM_ALG_ESTIMATEBIAS_2 0x4e
#define TMF8X2X_COM_ALG_ESTIMATEBIAS_2__estimate_bias_2__MASK  0xff
#define TMF8X2X_COM_ALG_ESTIMATEBIAS_2__estimate_bias_2__WIDTH 8
#define TMF8X2X_COM_ALG_ESTIMATEBIAS_2__estimate_bias_2__SHIFT 0
#define TMF8X2X_COM_ALG_ESTIMATEBIAS_2__estimate_bias_2__RESET 5

#define TMF8X2X_COM_ALG_ESTIMATEBIAS_3 0x4f
#define TMF8X2X_COM_ALG_ESTIMATEBIAS_3__estimate_bias_3__MASK  0xff
#define TMF8X2X_COM_ALG_ESTIMATEBIAS_3__estimate_bias_3__WIDTH 8
#define TMF8X2X_COM_ALG_ESTIMATEBIAS_3__estimate_bias_3__SHIFT 0
#define TMF8X2X_COM_ALG_ESTIMATEBIAS_3__estimate_bias_3__RESET 0

#define TMF8X2X_COM_ALG_TC_GAIN12_0 0x50
#define TMF8X2X_COM_ALG_TC_GAIN12_0__tc_gain12_0__MASK  0xff
#define TMF8X2X_COM_ALG_TC_GAIN12_0__tc_gain12_0__WIDTH 8
#define TMF8X2X_COM_ALG_TC_GAIN12_0__tc_gain12_0__SHIFT 0
#define TMF8X2X_COM_ALG_TC_GAIN12_0__tc_gain12_0__RESET 63

#define TMF8X2X_COM_ALG_TC_GAIN12_1 0x51
#define TMF8X2X_COM_ALG_TC_GAIN12_1__tc_gain12_1__MASK  0xff
#define TMF8X2X_COM_ALG_TC_GAIN12_1__tc_gain12_1__WIDTH 8
#define TMF8X2X_COM_ALG_TC_GAIN12_1__tc_gain12_1__SHIFT 0
#define TMF8X2X_COM_ALG_TC_GAIN12_1__tc_gain12_1__RESET 95

#define TMF8X2X_COM_ALG_TC_GAIN12_2 0x52
#define TMF8X2X_COM_ALG_TC_GAIN12_2__tc_gain12_2__MASK  0xff
#define TMF8X2X_COM_ALG_TC_GAIN12_2__tc_gain12_2__WIDTH 8
#define TMF8X2X_COM_ALG_TC_GAIN12_2__tc_gain12_2__SHIFT 0
#define TMF8X2X_COM_ALG_TC_GAIN12_2__tc_gain12_2__RESET 0

#define TMF8X2X_COM_ALG_TC_GAIN12_3 0x53
#define TMF8X2X_COM_ALG_TC_GAIN12_3__tc_gain12_3__MASK  0xff
#define TMF8X2X_COM_ALG_TC_GAIN12_3__tc_gain12_3__WIDTH 8
#define TMF8X2X_COM_ALG_TC_GAIN12_3__tc_gain12_3__SHIFT 0
#define TMF8X2X_COM_ALG_TC_GAIN12_3__tc_gain12_3__RESET 0

#define TMF8X2X_COM_ALG_CONVEX_NUMERATOR_0 0x54
#define TMF8X2X_COM_ALG_CONVEX_NUMERATOR_0__convex_numerator_0__MASK  0xff
#define TMF8X2X_COM_ALG_CONVEX_NUMERATOR_0__convex_numerator_0__WIDTH 8
#define TMF8X2X_COM_ALG_CONVEX_NUMERATOR_0__convex_numerator_0__SHIFT 0
#define TMF8X2X_COM_ALG_CONVEX_NUMERATOR_0__convex_numerator_0__RESET 3

#define TMF8X2X_COM_ALG_CONVEX_NUMERATOR_1 0x55
#define TMF8X2X_COM_ALG_CONVEX_NUMERATOR_1__convex_numerator_1__MASK  0xff
#define TMF8X2X_COM_ALG_CONVEX_NUMERATOR_1__convex_numerator_1__WIDTH 8
#define TMF8X2X_COM_ALG_CONVEX_NUMERATOR_1__convex_numerator_1__SHIFT 0
#define TMF8X2X_COM_ALG_CONVEX_NUMERATOR_1__convex_numerator_1__RESET 0

#define TMF8X2X_COM_ALG_CONVEX_NUMERATOR_2 0x56
#define TMF8X2X_COM_ALG_CONVEX_NUMERATOR_2__convex_numerator_2__MASK  0xff
#define TMF8X2X_COM_ALG_CONVEX_NUMERATOR_2__convex_numerator_2__WIDTH 8
#define TMF8X2X_COM_ALG_CONVEX_NUMERATOR_2__convex_numerator_2__SHIFT 0
#define TMF8X2X_COM_ALG_CONVEX_NUMERATOR_2__convex_numerator_2__RESET 0

#define TMF8X2X_COM_ALG_CONVEX_NUMERATOR_3 0x57
#define TMF8X2X_COM_ALG_CONVEX_NUMERATOR_3__convex_numerator_3__MASK  0xff
#define TMF8X2X_COM_ALG_CONVEX_NUMERATOR_3__convex_numerator_3__WIDTH 8
#define TMF8X2X_COM_ALG_CONVEX_NUMERATOR_3__convex_numerator_3__SHIFT 0
#define TMF8X2X_COM_ALG_CONVEX_NUMERATOR_3__convex_numerator_3__RESET 0

#define TMF8X2X_COM_ALG_CONVEX_DENOMINATOR_0 0x58
#define TMF8X2X_COM_ALG_CONVEX_DENOMINATOR_0__convex_denominator_0__MASK  0xff
#define TMF8X2X_COM_ALG_CONVEX_DENOMINATOR_0__convex_denominator_0__WIDTH 8
#define TMF8X2X_COM_ALG_CONVEX_DENOMINATOR_0__convex_denominator_0__SHIFT 0
#define TMF8X2X_COM_ALG_CONVEX_DENOMINATOR_0__convex_denominator_0__RESET 1

#define TMF8X2X_COM_ALG_CONVEX_DENOMINATOR_1 0x59
#define TMF8X2X_COM_ALG_CONVEX_DENOMINATOR_1__convex_denominator_1__MASK  0xff
#define TMF8X2X_COM_ALG_CONVEX_DENOMINATOR_1__convex_denominator_1__WIDTH 8
#define TMF8X2X_COM_ALG_CONVEX_DENOMINATOR_1__convex_denominator_1__SHIFT 0
#define TMF8X2X_COM_ALG_CONVEX_DENOMINATOR_1__convex_denominator_1__RESET 0

#define TMF8X2X_COM_ALG_CONVEX_DENOMINATOR_2 0x5a
#define TMF8X2X_COM_ALG_CONVEX_DENOMINATOR_2__convex_denominator_2__MASK  0xff
#define TMF8X2X_COM_ALG_CONVEX_DENOMINATOR_2__convex_denominator_2__WIDTH 8
#define TMF8X2X_COM_ALG_CONVEX_DENOMINATOR_2__convex_denominator_2__SHIFT 0
#define TMF8X2X_COM_ALG_CONVEX_DENOMINATOR_2__convex_denominator_2__RESET 0

#define TMF8X2X_COM_ALG_CONVEX_DENOMINATOR_3 0x5b
#define TMF8X2X_COM_ALG_CONVEX_DENOMINATOR_3__convex_denominator_3__MASK  0xff
#define TMF8X2X_COM_ALG_CONVEX_DENOMINATOR_3__convex_denominator_3__WIDTH 8
#define TMF8X2X_COM_ALG_CONVEX_DENOMINATOR_3__convex_denominator_3__SHIFT 0
#define TMF8X2X_COM_ALG_CONVEX_DENOMINATOR_3__convex_denominator_3__RESET 0

#define TMF8X2X_COM_ALG_MIN_EFFECTIVE_BASELINE_0 0x5c
#define TMF8X2X_COM_ALG_MIN_EFFECTIVE_BASELINE_0__min_effective_baseline_0__MASK  0xff
#define TMF8X2X_COM_ALG_MIN_EFFECTIVE_BASELINE_0__min_effective_baseline_0__WIDTH 8
#define TMF8X2X_COM_ALG_MIN_EFFECTIVE_BASELINE_0__min_effective_baseline_0__SHIFT 0
#define TMF8X2X_COM_ALG_MIN_EFFECTIVE_BASELINE_0__min_effective_baseline_0__RESET 35

#define TMF8X2X_COM_ALG_MIN_EFFECTIVE_BASELINE_1 0x5d
#define TMF8X2X_COM_ALG_MIN_EFFECTIVE_BASELINE_1__min_effective_baseline_1__MASK  0xff
#define TMF8X2X_COM_ALG_MIN_EFFECTIVE_BASELINE_1__min_effective_baseline_1__WIDTH 8
#define TMF8X2X_COM_ALG_MIN_EFFECTIVE_BASELINE_1__min_effective_baseline_1__SHIFT 0
#define TMF8X2X_COM_ALG_MIN_EFFECTIVE_BASELINE_1__min_effective_baseline_1__RESET 0

#define TMF8X2X_COM_ALG_MIN_EFFECTIVE_BASELINE_2 0x5e
#define TMF8X2X_COM_ALG_MIN_EFFECTIVE_BASELINE_2__min_effective_baseline_2__MASK  0xff
#define TMF8X2X_COM_ALG_MIN_EFFECTIVE_BASELINE_2__min_effective_baseline_2__WIDTH 8
#define TMF8X2X_COM_ALG_MIN_EFFECTIVE_BASELINE_2__min_effective_baseline_2__SHIFT 0
#define TMF8X2X_COM_ALG_MIN_EFFECTIVE_BASELINE_2__min_effective_baseline_2__RESET 0

#define TMF8X2X_COM_ALG_MIN_EFFECTIVE_BASELINE_3 0x5f
#define TMF8X2X_COM_ALG_MIN_EFFECTIVE_BASELINE_3__min_effective_baseline_3__MASK  0xff
#define TMF8X2X_COM_ALG_MIN_EFFECTIVE_BASELINE_3__min_effective_baseline_3__WIDTH 8
#define TMF8X2X_COM_ALG_MIN_EFFECTIVE_BASELINE_3__min_effective_baseline_3__SHIFT 0
#define TMF8X2X_COM_ALG_MIN_EFFECTIVE_BASELINE_3__min_effective_baseline_3__RESET 0

#define TMF8X2X_COM_ALG_SPARE_43_0 0x60
#define TMF8X2X_COM_ALG_SPARE_43_0__spare_43_0__MASK  0xff
#define TMF8X2X_COM_ALG_SPARE_43_0__spare_43_0__WIDTH 8
#define TMF8X2X_COM_ALG_SPARE_43_0__spare_43_0__SHIFT 0
#define TMF8X2X_COM_ALG_SPARE_43_0__spare_43_0__RESET 0

#define TMF8X2X_COM_ALG_SPARE_43_1 0x61
#define TMF8X2X_COM_ALG_SPARE_43_1__spare_43_1__MASK  0xff
#define TMF8X2X_COM_ALG_SPARE_43_1__spare_43_1__WIDTH 8
#define TMF8X2X_COM_ALG_SPARE_43_1__spare_43_1__SHIFT 0
#define TMF8X2X_COM_ALG_SPARE_43_1__spare_43_1__RESET 0

#define TMF8X2X_COM_ALG_SPARE_43_2 0x62
#define TMF8X2X_COM_ALG_SPARE_43_2__spare_43_2__MASK  0xff
#define TMF8X2X_COM_ALG_SPARE_43_2__spare_43_2__WIDTH 8
#define TMF8X2X_COM_ALG_SPARE_43_2__spare_43_2__SHIFT 0
#define TMF8X2X_COM_ALG_SPARE_43_2__spare_43_2__RESET 0

#define TMF8X2X_COM_ALG_SPARE_43_3 0x63
#define TMF8X2X_COM_ALG_SPARE_43_3__spare_43_3__MASK  0xff
#define TMF8X2X_COM_ALG_SPARE_43_3__spare_43_3__WIDTH 8
#define TMF8X2X_COM_ALG_SPARE_43_3__spare_43_3__SHIFT 0
#define TMF8X2X_COM_ALG_SPARE_43_3__spare_43_3__RESET 0

#define TMF8X2X_COM_ALG_SPARE_44_0 0x64
#define TMF8X2X_COM_ALG_SPARE_44_0__spare_44_0__MASK  0xff
#define TMF8X2X_COM_ALG_SPARE_44_0__spare_44_0__WIDTH 8
#define TMF8X2X_COM_ALG_SPARE_44_0__spare_44_0__SHIFT 0
#define TMF8X2X_COM_ALG_SPARE_44_0__spare_44_0__RESET 0

#define TMF8X2X_COM_ALG_SPARE_44_1 0x65
#define TMF8X2X_COM_ALG_SPARE_44_1__spare_44_1__MASK  0xff
#define TMF8X2X_COM_ALG_SPARE_44_1__spare_44_1__WIDTH 8
#define TMF8X2X_COM_ALG_SPARE_44_1__spare_44_1__SHIFT 0
#define TMF8X2X_COM_ALG_SPARE_44_1__spare_44_1__RESET 0

#define TMF8X2X_COM_ALG_SPARE_44_2 0x66
#define TMF8X2X_COM_ALG_SPARE_44_2__spare_44_2__MASK  0xff
#define TMF8X2X_COM_ALG_SPARE_44_2__spare_44_2__WIDTH 8
#define TMF8X2X_COM_ALG_SPARE_44_2__spare_44_2__SHIFT 0
#define TMF8X2X_COM_ALG_SPARE_44_2__spare_44_2__RESET 0

#define TMF8X2X_COM_ALG_SPARE_44_3 0x67
#define TMF8X2X_COM_ALG_SPARE_44_3__spare_44_3__MASK  0xff
#define TMF8X2X_COM_ALG_SPARE_44_3__spare_44_3__WIDTH 8
#define TMF8X2X_COM_ALG_SPARE_44_3__spare_44_3__SHIFT 0
#define TMF8X2X_COM_ALG_SPARE_44_3__spare_44_3__RESET 0

#define TMF8X2X_COM_ALG_SPARE_45_0 0x68
#define TMF8X2X_COM_ALG_SPARE_45_0__spare_45_0__MASK  0xff
#define TMF8X2X_COM_ALG_SPARE_45_0__spare_45_0__WIDTH 8
#define TMF8X2X_COM_ALG_SPARE_45_0__spare_45_0__SHIFT 0
#define TMF8X2X_COM_ALG_SPARE_45_0__spare_45_0__RESET 0

#define TMF8X2X_COM_ALG_SPARE_45_1 0x69
#define TMF8X2X_COM_ALG_SPARE_45_1__spare_45_1__MASK  0xff
#define TMF8X2X_COM_ALG_SPARE_45_1__spare_45_1__WIDTH 8
#define TMF8X2X_COM_ALG_SPARE_45_1__spare_45_1__SHIFT 0
#define TMF8X2X_COM_ALG_SPARE_45_1__spare_45_1__RESET 0

#define TMF8X2X_COM_ALG_SPARE_45_2 0x6a
#define TMF8X2X_COM_ALG_SPARE_45_2__spare_45_2__MASK  0xff
#define TMF8X2X_COM_ALG_SPARE_45_2__spare_45_2__WIDTH 8
#define TMF8X2X_COM_ALG_SPARE_45_2__spare_45_2__SHIFT 0
#define TMF8X2X_COM_ALG_SPARE_45_2__spare_45_2__RESET 0

#define TMF8X2X_COM_ALG_SPARE_45_3 0x6b
#define TMF8X2X_COM_ALG_SPARE_45_3__spare_45_3__MASK  0xff
#define TMF8X2X_COM_ALG_SPARE_45_3__spare_45_3__WIDTH 8
#define TMF8X2X_COM_ALG_SPARE_45_3__spare_45_3__SHIFT 0
#define TMF8X2X_COM_ALG_SPARE_45_3__spare_45_3__RESET 0

#define TMF8X2X_COM_ALG_SPARE_46_0 0x6c
#define TMF8X2X_COM_ALG_SPARE_46_0__spare_46_0__MASK  0xff
#define TMF8X2X_COM_ALG_SPARE_46_0__spare_46_0__WIDTH 8
#define TMF8X2X_COM_ALG_SPARE_46_0__spare_46_0__SHIFT 0
#define TMF8X2X_COM_ALG_SPARE_46_0__spare_46_0__RESET 0

#define TMF8X2X_COM_ALG_SPARE_46_1 0x6d
#define TMF8X2X_COM_ALG_SPARE_46_1__spare_46_1__MASK  0xff
#define TMF8X2X_COM_ALG_SPARE_46_1__spare_46_1__WIDTH 8
#define TMF8X2X_COM_ALG_SPARE_46_1__spare_46_1__SHIFT 0
#define TMF8X2X_COM_ALG_SPARE_46_1__spare_46_1__RESET 0

#define TMF8X2X_COM_ALG_SPARE_46_2 0x6e
#define TMF8X2X_COM_ALG_SPARE_46_2__spare_46_2__MASK  0xff
#define TMF8X2X_COM_ALG_SPARE_46_2__spare_46_2__WIDTH 8
#define TMF8X2X_COM_ALG_SPARE_46_2__spare_46_2__SHIFT 0
#define TMF8X2X_COM_ALG_SPARE_46_2__spare_46_2__RESET 0

#define TMF8X2X_COM_ALG_SPARE_46_3 0x6f
#define TMF8X2X_COM_ALG_SPARE_46_3__spare_46_3__MASK  0xff
#define TMF8X2X_COM_ALG_SPARE_46_3__spare_46_3__WIDTH 8
#define TMF8X2X_COM_ALG_SPARE_46_3__spare_46_3__SHIFT 0
#define TMF8X2X_COM_ALG_SPARE_46_3__spare_46_3__RESET 0

#endif // TMF8X2X_CONFIG_PAGE_COMMON_H
