// This file has not only been generated automatically, it has also been patched automatically on top of that: All addresses have been multiplied by 4 to match the AMBA bus addressing


// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!         THIS FILE IS AUTOMATICALLY GENERATED         !!
// !!              DO NOT EDIT THIS FILE                   !!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#ifndef TMF8X2X_HISTOGRAM_REGISTERS_H
#define TMF8X2X_HISTOGRAM_REGISTERS_H

#define TMF8X2X_COM_SUBPACKET_NUMBER 0x24
#define TMF8X2X_COM_SUBPACKET_NUMBER__subpacket_number__MASK  0xff
#define TMF8X2X_COM_SUBPACKET_NUMBER__subpacket_number__WIDTH 8
#define TMF8X2X_COM_SUBPACKET_NUMBER__subpacket_number__SHIFT 0
#define TMF8X2X_COM_SUBPACKET_NUMBER__subpacket_number__RESET 0

#define TMF8X2X_COM_SUBPACKET_PAYLOAD 0x25
#define TMF8X2X_COM_SUBPACKET_PAYLOAD__subpacket_payload__MASK  0xff
#define TMF8X2X_COM_SUBPACKET_PAYLOAD__subpacket_payload__WIDTH 8
#define TMF8X2X_COM_SUBPACKET_PAYLOAD__subpacket_payload__SHIFT 0
#define TMF8X2X_COM_SUBPACKET_PAYLOAD__subpacket_payload__RESET 0

#define TMF8X2X_COM_SUBPACKET_CFG_IDX 0x26
#define TMF8X2X_COM_SUBPACKET_CFG_IDX__statistics_cfg_idx__MASK  0xff
#define TMF8X2X_COM_SUBPACKET_CFG_IDX__statistics_cfg_idx__WIDTH 8
#define TMF8X2X_COM_SUBPACKET_CFG_IDX__statistics_cfg_idx__SHIFT 0
#define TMF8X2X_COM_SUBPACKET_CFG_IDX__statistics_cfg_idx__RESET 0

#define TMF8X2X_COM_PAYLOAD_0 0x27
#define TMF8X2X_COM_PAYLOAD_0__payload_0__MASK  0xff
#define TMF8X2X_COM_PAYLOAD_0__payload_0__WIDTH 8
#define TMF8X2X_COM_PAYLOAD_0__payload_0__SHIFT 0
#define TMF8X2X_COM_PAYLOAD_0__payload_0__RESET 0

#endif // TMF8X2X_HISTOGRAM_REGISTERS_H
